USE master;

CREATE DATABASE PV_522_DDL
ON
(
	NAME		=	PV_522_DDL,
	FILENAME	=	'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_522_DDL.mdf',
	SIZE		=	8MB,
	MAXSIZE		=	500MB,
	FILEGROWTH	=	8MB
)
LOG ON
(
	NAME		=	PV_522_DDL_LOG,
	FILENAME	=	'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_522_DDL_LOG.ldf',
	SIZE		=	8MB,
	MAXSIZE		=	500MB,
	FILEGROWTH	=	8MB
);